#define PREFKEY_SPIELZAEHLER_FORMAT @"spielzaehler_%d"
#define PREFKEY_GEWONNENZAEHLER_FORMAT @"gewonnenzaehler_%d"
#define PREFKEY_SOUND_AN @"soundAn"
#define PREFKEY_GITTER_AN @"gitterAn"
#define PREFKEY_SPIELLEVEL @"spielLevel"
#define PREFKEY_FARBSCHEMA @"farbschema"
